# -*- coding: utf-8 -*-
"""NCI_vllm0.18.0_stetup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6eo87TS4laOa2UiAFznp-EehbMod2Bk

# Easy Method (3h)

gpuhopper + Jobfs size: 200GB
"""

# Your project id
cd /scratch/xxx/xxx/

module purge
module load python3/3.12.1
module load cuda/12.8.0
module load gcc/12.2.0
export CC=$(which gcc)
export CXX=$(which g++)
export TORCH_CUDA_ARCH_LIST="9.0"

export MY_CACHE_DIR="$PBS_JOBFS/cache"
mkdir -p $MY_CACHE_DIR
export TMPDIR=$PBS_JOBFS
export PIP_CACHE_DIR="$MY_CACHE_DIR/pip"
export UV_CACHE_DIR="$MY_CACHE_DIR/uv"
export HF_HOME="$MY_CACHE_DIR/huggingface"
export TORCH_EXTENSIONS_DIR="$MY_CACHE_DIR/torch_extensions"
export CUDA_CACHE_PATH="$MY_CACHE_DIR/nv_compute_cache"
export CMAKE_BUILD_CACHE="$MY_CACHE_DIR/cmake"
export MAX_JOBS=90

pip install uv
uv venv vllm_venv
source vllm_venv/bin/activate

uv pip install vllm==0.18.0

"""# Quick Method (1h or less)

## login node:
"""

cd /scratch/xxx/xxx/

module purge
module load python3/3.12.1
module load cuda/12.8.0
module load gcc/12.2.0
export CC=$(which gcc)
export CXX=$(which g++)
export TORCH_CUDA_ARCH_LIST="9.0"

pip install uv
uv venv vllm_venv
source vllm_venv/bin/activate


nano requirements_vllm.txt
uv pip install -r requirements_vllm.txt

"""## nano requirements_vllm.txt"""

regex
cachetools
psutil
sentencepiece
numpy
requests >= 2.26.0
tqdm
blake3
py-cpuinfo
transformers >= 4.56.0, < 5
tokenizers >= 0.21.1
protobuf >= 5.29.6, !=6.30.*, !=6.31.*, !=6.32.*, !=6.33.0.*, !=6.33.1.*, !=6.33.2.*, !=6.33.3.*, !=6.33.4.*
fastapi[standard] >= 0.115.0
aiohttp >= 3.13.3
openai >= 2.0.0
pydantic >= 2.12.0
prometheus_client >= 0.18.0
pillow
prometheus-fastapi-instrumentator >= 7.0.0
tiktoken >= 0.6.0
lm-format-enforcer == 0.11.3
llguidance >= 1.3.0, < 1.4.0; platform_machine == "x86_64" or platform_machine == "arm64"
outlines_core == 0.2.11
diskcache == 5.6.3
lark == 1.2.2
xgrammar >= 0.1.32, < 1.0.0; platform_machine == "x86_64" or platform_machine == "aarch64"
typing_extensions >= 4.10
filelock >= 3.16.1
partial-json-parser
pyzmq >= 25.0.0
msgspec
gguf >= 0.17.0
mistral_common[image] >= 1.10.0
opencv-python-headless >= 4.13.0
pyyaml
six >= 1.16.0; python_version > '3.11'
setuptools >= 77.0.3, < 81.0.0
einops
compressed-tensors == 0.14.0.1
depyf == 0.20.0
cloudpickle
watchfiles
python-json-logger
ninja
pybase64
cbor2
ijson
setproctitle
openai-harmony >= 0.0.3
anthropic >= 0.71.0
model-hosting-container-standards >= 0.1.13, < 1.0.0
mcp
opentelemetry-sdk >= 1.27.0
opentelemetry-api >= 1.27.0
opentelemetry-exporter-otlp >= 1.27.0
opentelemetry-semantic-conventions-ai >= 0.4.1
cmake >= 3.26.1
setuptools-scm >= 8
torch == 2.10.0
wheel
jinja2 >= 3.1.6
build

"""## CPU node

megamembw

Jobfs size: 200GB
"""

cd /scratch/xxx/xxx/

module purge
module load python3/3.12.1
module load cuda/12.8.0
module load gcc/12.2.0
export CC=$(which gcc)
export CXX=$(which g++)
export TORCH_CUDA_ARCH_LIST="9.0"

source vllm_venv/bin/activate

export MY_CACHE_DIR="$PBS_JOBFS/cache"
mkdir -p $MY_CACHE_DIR
export TMPDIR=$PBS_JOBFS
export PIP_CACHE_DIR="$MY_CACHE_DIR/pip"
export UV_CACHE_DIR="$MY_CACHE_DIR/uv"
export HF_HOME="$MY_CACHE_DIR/huggingface"
export TORCH_EXTENSIONS_DIR="$MY_CACHE_DIR/torch_extensions"
export CUDA_CACHE_PATH="$MY_CACHE_DIR/nv_compute_cache"
export CMAKE_BUILD_CACHE="$MY_CACHE_DIR/cmake"

uv pip install vllm==0.18.0

"""# Other

## Check
"""

# 1. 清理并加载基础环境
module purge
module load python3/3.12.1 cuda/12.8.0 gcc/12.2.0

# 2. 重新激活虚拟环境（这一步会将虚拟环境的路径重新插到 PATH 的最前面）
source /scratch/xxx/xxx/vllm18_venv/bin/activate

# 3. 设置 H200 专用变量
export TORCH_CUDA_ARCH_LIST="9.0"
unset PYTHONPATH

# 4. 再次验证
python3 -c "import torch; print(f'Device: {torch.cuda.get_device_name(0)}'); print(f'CUDA version: {torch.version.cuda}')"